#import "DataStorage.h"

#ifdef RCT_NEW_ARCH_ENABLED
#import <ReactCodegen/DataStorage/DataStorage.h>
#endif

// Import the Swift module header - generated by Xcode
#if __has_include("DataStorage-Swift.h")
#import "DataStorage-Swift.h"
#else
#import <DataStorage/DataStorage-Swift.h>
#endif

@implementation DataStorage

RCT_EXPORT_MODULE(DataStorage)

#ifdef RCT_NEW_ARCH_ENABLED
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativeDataStorageSpecJSI>(params);
}
#endif

+ (BOOL)requiresMainQueueSetup
{
    return NO;
}

- (void)getItem:(NSString *)key
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject
{
    if (@available(iOS 17.0, *)) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            @try {
                DataStorageManager *manager = [DataStorageManager shared];
                NSError *error = nil;
                id value = [manager getItemWithKey:key error:&error];
                
                if (error) {
                    reject(@"GET_ITEM_ERROR", error.localizedDescription, error);
                    return;
                }
                
                // If value is NSNull, return nil to JavaScript
                if (value == nil || [value isKindOfClass:[NSNull class]]) {
                    resolve([NSNull null]);
                } else {
                    resolve(value);
                }
            } @catch (NSException *exception) {
                reject(@"GET_ITEM_EXCEPTION", exception.reason, nil);
            }
        });
    } else {
        reject(@"UNSUPPORTED_IOS_VERSION", @"DataStorage requires iOS 17.0 or later", nil);
    }
}

- (void)setItem:(NSString *)key
          value:(NSDictionary *)value
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject
{
    if (@available(iOS 17.0, *)) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            @try {
                DataStorageManager *manager = [DataStorageManager shared];
                NSError *error = nil;
                [manager setItemWithKey:key value:value error:&error];
                
                if (error) {
                    reject(@"SET_ITEM_ERROR", error.localizedDescription, error);
                    return;
                }
                
                resolve(nil);
            } @catch (NSException *exception) {
                reject(@"SET_ITEM_EXCEPTION", exception.reason, nil);
            }
        });
    } else {
        reject(@"UNSUPPORTED_IOS_VERSION", @"DataStorage requires iOS 17.0 or later", nil);
    }
}

- (void)removeItem:(NSString *)key
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject
{
    if (@available(iOS 17.0, *)) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            @try {
                DataStorageManager *manager = [DataStorageManager shared];
                NSError *error = nil;
                [manager removeItemWithKey:key error:&error];
                
                if (error) {
                    reject(@"REMOVE_ITEM_ERROR", error.localizedDescription, error);
                    return;
                }
                
                resolve(nil);
            } @catch (NSException *exception) {
                reject(@"REMOVE_ITEM_EXCEPTION", exception.reason, nil);
            }
        });
    } else {
        reject(@"UNSUPPORTED_IOS_VERSION", @"DataStorage requires iOS 17.0 or later", nil);
    }
}

- (void)getAllKeys:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject
{
    if (@available(iOS 17.0, *)) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            @try {
                DataStorageManager *manager = [DataStorageManager shared];
                NSError *error = nil;
                NSArray<NSString *> *keys = [manager getAllKeysAndReturnError:&error];
                
                if (error) {
                    reject(@"GET_ALL_KEYS_ERROR", error.localizedDescription, error);
                    return;
                }
                
                resolve(keys);
            } @catch (NSException *exception) {
                reject(@"GET_ALL_KEYS_EXCEPTION", exception.reason, nil);
            }
        });
    } else {
        reject(@"UNSUPPORTED_IOS_VERSION", @"DataStorage requires iOS 17.0 or later", nil);
    }
}

- (void)clear:(RCTPromiseResolveBlock)resolve
       reject:(RCTPromiseRejectBlock)reject
{
    if (@available(iOS 17.0, *)) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            @try {
                DataStorageManager *manager = [DataStorageManager shared];
                NSError *error = nil;
                [manager clearAndReturnError:&error];
                
                if (error) {
                    reject(@"CLEAR_ERROR", error.localizedDescription, error);
                    return;
                }
                
                resolve(nil);
            } @catch (NSException *exception) {
                reject(@"CLEAR_EXCEPTION", exception.reason, nil);
            }
        });
    } else {
        reject(@"UNSUPPORTED_IOS_VERSION", @"DataStorage requires iOS 17.0 or later", nil);
    }
}

@end
